import Link from "next/link";
import "./globals.css";
import Image from "next/image";

export const metadata = {
  title: "My Super Blog",
  description: "Generated by create next app",
};

const header = (
  <header>
    <Link href={"/"}>
      <div className=" text-center bg-slate-800 p-8 my-6 rounded-md">
        <Image
          src={"/logo.png"}
          width={40}
          height={40}
          alt=""
          className=" mx-auto"
        />

        <h1 className="text-2xl text-white font-bold mt-4">Jacks Blog</h1>

        <p className="text-slate-300">💡 Welcome to my tech blog 🍺</p>
      </div>
    </Link>
  </header>
);

const footer = (
  <footer>
    <div>
      <h3 className="border-t border-slate-400 mt-12 py-6 text-center text-slate-400">
        Developed by Pixegami
      </h3>
    </div>
  </footer>
);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="mx-auto max-w-2xl px-6">
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
